apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: n1o07rc2o-nodejs 
  janus-idp.io/tekton: n1o07rc2o-nodejs
  backstage.io/kubernetes-id: n1o07rc2o-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: n1o07rc2o-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml