apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: n1o07rc2o-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: n1o07rc2o-nodejs 
  name: n1o07rc2o-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: n1o07rc2o-nodejs 
